version: '3.8'

volumes:
  getraenkekasse-db:

services:
  getraenkekasse-db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: johndoe
      POSTGRES_DB: getraenkekasse
    volumes:
      - getraenkekasse-db:/var/lib/postgresql/data
    networks:
      - webnet

  getraenkekasse-web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=getraenkekasse-db
      - DB_NAME=getraenkekasse
      - DB_USER=admin
      - DB_PASS=johndoe
    depends_on:
      - getraenkekasse-db
    networks:
      - webnet



networks:
  webnet:
